# Generated by Django 4.1.2 on 2023-11-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('idreserva', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=20)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.CharField(max_length=30)),
                ('departamento', models.CharField(max_length=30)),
                ('doctor', models.CharField(max_length=30)),
                ('comentario', models.CharField(max_length=50)),
            ],
        ),
    ]
