# Generated by Django 4.1.2 on 2023-11-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GlobalMed', '0002_doctores_alter_reserva_comentario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='departamentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_dep', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctores',
            name='departamento',
        ),
        migrations.AddField(
            model_name='doctores',
            name='id_dep',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
