# Generated by Django 4.1.2 on 2023-11-14 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GlobalMed', '0003_departamentos_remove_doctores_departamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='doctor',
        ),
        migrations.AddField(
            model_name='reserva',
            name='id_departamento',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='id_doctor',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
