# Generated by Django 4.1.2 on 2023-11-14 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GlobalMed', '0004_remove_reserva_departamento_remove_reserva_doctor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='id_departamento',
            new_name='departamento',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='id_doctor',
            new_name='doctor',
        ),
    ]
